### ISSUE TITLE
question... Cannot read property 'sha' of undefined

### ISSUE THREAD

**Issue by willwade** [gmaclennan/hubfs.js#1]
I don't think this is a hubfs.js issue.. But everything was going swell for me on development (pushing a file to GitHub using this excellent library) - now - seemingly all of a sudden (we know thats not going to be true right?!) I'm getting this 'TypeError: Cannot read property 'sha' of undefined' error - any suggestions on what might be wrong??

will

/Users/willwade/bin/OpenATBackend/node_modules/hubfs.js/index.js:363
        cb(err, commitSha, tree.sha)
                               ^

TypeError: Cannot read property 'sha' of undefined
    at /Users/willwade/bin/OpenATBackend/node_modules/hubfs.js/index.js:363:32
    at /Users/willwade/bin/OpenATBackend/node_modules/octokat/dist/node/octokat.js:75:18
    at /Users/willwade/bin/OpenATBackend/node_modules/octokat/dist/node/request.js:241:20
    at xhr.onreadystatechange (/Users/willwade/bin/OpenATBackend/node_modules/octokat/dist/node/request.js:45:18)
    at dispatchEvent (/Users/willwade/bin/OpenATBackend/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/willwade/bin/OpenATBackend/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/willwade/bin/OpenATBackend/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

**Comment by willwade** [comment]
ok I've been an idiot - but leaving this for the sake of any other idiots to come: you probably have defined the wrong path. I had put a / as the initial path to save my GitHub file.
